services:
  - type: web
    name: hifas-jewellery
    env: docker
    repo: https://github.com/hifas86/Hifas-Jewellery
    plan: free

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: goldtrade.settings
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.13
      - key: DATABASE_URL
        fromDatabase:
          name: hifas-db
          property: connectionString

    healthCheckPath: /
    disk:
      name: media
      mountPath: /app/media
      sizeGB: 1

databases:
  - name: hifas-db
    databaseName: hifas_db
    user: hifas_user
